#!/bin/sh

openvpn_port="$(uci -q get openvpn-server.myvpn.port)"
[ -z "$openvpn_port" ] && openvpn_port=1194

uci -q batch <<-EOF >/dev/null
	delete network.vpn0
	commit network
	delete firewall.openvpn
	set firewall.openvpn=rule
	set firewall.openvpn.name='openvpn'
	set firewall.openvpn.target='ACCEPT'
	set firewall.openvpn.src='wan'
	set firewall.openvpn.proto='tcp udp'
	set firewall.openvpn.dest_port="$openvpn_port"
	delete firewall.openvpn_zone
	set firewall.openvpn_zone=zone
	set firewall.openvpn_zone.name='openvpn'
	set firewall.openvpn_zone.input='ACCEPT'
	set firewall.openvpn_zone.forward='ACCEPT'
	set firewall.openvpn_zone.output='ACCEPT'
	add_list firewall.openvpn_zone.device='tun0'
	delete firewall.vpntowan
	set firewall.vpntowan=forwarding
	set firewall.vpntowan.src='openvpn'
	set firewall.vpntowan.dest='wan'
	delete firewall.vpntolan
	set firewall.vpntolan=forwarding
	set firewall.vpntolan.src='openvpn'
	set firewall.vpntolan.dest='lan'
	delete firewall.lantovpn
	set firewall.lantovpn=forwarding
	set firewall.lantovpn.src='lan'
	set firewall.lantovpn.dest='openvpn'
	commit firewall
EOF

if [ ! -f "/etc/openvpn/pki/ca.crt" ]; then
	sh /etc/openvpn/renewcert.sh >/dev/null 2>&1
fi

if [ -x /etc/init.d/openvpn ]; then
	/etc/init.d/openvpn disable 2>/dev/null
	/etc/init.d/openvpn stop 2>/dev/null
fi

rm -f /tmp/luci-indexcache*
exit 0
